export const cartConstants = {
    ADD_TO_CART: 'ADD_TO_CART',
    RENDER_TO_CART: 'RENDER_TO_CART',
    ADD_QUANTITY_CART: 'ADD_QUANTITY_CART',
    SUB_QUANTITY_CART: 'SUB_QUANTITY_CART',
    POST_CART_TO_DB: 'POST_CART_TO_DB'
}
